version: "3.3"
services:
  api:
    build: ./sentiment-analysis-api/.
    ports:
      - "8000:8000"
  web:
    build: ./sentiment-analysis-web/.
    ports:
      - "3000:3000"
    links:
      - "api:web"